#!/bin/bash

cd /home/ec2-user/procrastinate.website
sudo git pull
sudo rm -rf /var/www/html
sudo mkdir /var/www/html
sudo cp -R /home/ec2-user/procrastinate.website/www/* /var/www/html/
sudo cp www/.htaccess /var/www/html/.htaccess
echo "Updated /var/www/html"
